map_index:
    path: /map
    defaults: { _controller: AppBundle:Map:index }

locations_index:
    path: /rest/locations
    defaults: { _controller: AppBundle:Rest/Locations:list, _format: json }

admin_index:
    path: /admin
    defaults: { _controller: AppBundle:Admin:index }

upload_rest_upload:
    path: /rest/upload
    defaults: { _controller: AppBundle:Rest/Upload:upload, _format: json }

