services:
    pimterest.api.reader.twitter:
        class: AppBundle\Twitter\TwitterReader
        arguments:
            - %twitter.tag%
    pimterest.reader.instagram:
        class: AppBundle\Service\InstagramReader
