services:
    pimterest.api.reader.twitter:
        class: AppBundle\Twitter\TwitterReader
        arguments:
            - %twitter.tag%
    pimterest.reader.instagram:
        class: AppBundle\Instagram\InstagramReader
        arguments:
            - %instagram.tag%
            - %instagram.api_key%
            - %instagram.api_secret%
            - %instagram.api_callback%
    pimterest.repository.contribution:
        class: AppBundle\Repository\ContributionRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ['AppBundle\Entity\Contribution']
